<!--
Nombre: Serfio Familiar
Curso: DAW1
Fecha: 26/03/2025
Ejercicio: 4
-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
    <!ELEMENT vuelos (vuelo*)>  
    <!ELEMENT vuelo (origen, destino)>  
    <!ELEMENT origen (#PCDATA)>  
    <!ELEMENT destino (#PCDATA)>  
]>
<vuelos>
    <vuelo>
        <origen>Valencia (VLC)</origen>
        <destino>Londres Heathrow (LHR)</destino>
    </vuelo>
    <vuelo>
        <origen>Paris Charles de Gaulle (CDG)</origen>
        <destino>Berlin Sch√∂nefeld (SFX)</destino>
    </vuelo>
</vuelos>