<!--
Nombre: Serfio Familiar
Curso: DAW1
Fecha: 26/03/2025
Ejercicio: 6
-->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
    <!ELEMENT pais (nombre, unionEuropea?, otan?)> 
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT unionEuropea EMPTY> 
    <!ELEMENT otan EMPTY> 
]>
<paises>
    <pais>
        <nombre>Espa√±a</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>